### ISSUE TITLE
About device_mappings.csv for UNSW IoT Traces dataset

### ISSUE THREAD

**Issue by liuxyu** [dilawer11/iot-device-fingerprinting#1]
This project is awesome. But I have some question about the UNSW dataset. UNSW dataset only provided a devices list of MAC address of each device. However, in CSV2FeatureData.py of this project, a device_mappings.csv of device IP address should be provided. So my question is how to use UNSW dataset in this project? Should I manually make a device to IP mapping file?

**Comment by dilawer11** [comment]
Hi,

Thankyou for reaching out. Yes I remember the UNSW dataset provides a MAC
address of each device. I created IP address mapping based on the MAC
address of each device using the MAC src and MAC dst field in the PCAP and
you can do the same to create one for yourself. I am also attaching the
mapping I used in case this helps you out

Best,
